openapi: 3.0.1
info:
  title: API de estados
  description: API para descrever um estado. Inclui sua região, área, população e capital.
  version: 0.0.1
  contact: 
    name: Marcele Montalvão Matos
    email: marcele.matos.pb@compasso.com.br
servers: 
- url: http://localhost:8080
  description: API de estados
paths:
  /api/states:
    get:
      summary: Busca todos os estados cadastrados.
      responses: 
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Estado"
    post: 
      summary: Cria um novo estado
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                regiao:
                  type: string
                populacao:
                  type: integer
                capital:
                  type: string
                area:
                  type: integer
      responses:
        201: 
          description: "Sucesso"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Estado"
        400:
          description: "Não foi possível criar estado"
  /api/states{id}:
    parameters:
      - name: id
        in: path
        schema:
          type: integer
        required: true
    get:
      summary: Recupera uma entidade pelo ID
      responses:
        200:
          description: Sucesso
          content: 
            application/json:
              schema:
                $ref: "#/components/schemas/Estado"
        404:            
          description: Estado não encontrado
          content:
            application/json:
              example: "Not Found"
    put:
      summary: Atualiza uma entidade pelo ID
      responses:
        204:
           description: Sucesso
        404:
          description: Não foi possível atualizar o estado
          content:
            application/json:
              example: "Not Found" 
    delete:
      summary: Deleta uma entidade pelo ID
      responses:
        204:
           description: Sucesso
        404:
          description: Não foi possível atualizar o estado
          content:
            application/json:
              example: "Not Found" 
  /api/states/:
    parameters:
      - name: regiao
        in: query
        schema:
          type: string
          enum: 
            - Sul
            - Sudeste
            - Nordeste
            - Norte
            - Centro-Oeste
        required: false
      - name: sort
        in: query
        schema:
          type: string
          enum:
            - populacao,desc 
            - area, desc
    get:
      summary: Ordena os estados cadastrados
      responses: 
        200:
          description: Sucesso
          content: 
            application/json:
              schema:
                $ref: "#/components/schemas/Estado"
        404:            
          description: Estado não encontrado
          content:
            application/json:
              example: "Not Found"  
components:
  schemas:
    Estado:
      type: object
      properties:
        id:
          type: integer
        nome:
          type: string
        regiao:
          type: string
        populacao:
          type: integer
        capital:
          type: string
        area:
          type: integer